kind: FreeFlowPolicySequence
apiVersion: api.ibm.com/v1
metadata:
  name: policy-sequence
  namespace: orders-api
  version: '1'
  tags: []
  labels:
    gatewayTypes:
      - nano
spec:
  main:
    - $ref: orders-api:invoke-order-system:1.0
  monitoring:
    $ref: orders-api:telemetry:1.0
